[package]
name = "dcrypt-sign"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Digital Signature Schemes for the dcrypt library"
repository.workspace = true
license.workspace = true
publish = true


[features]
trace = []
default = ["std", "traditional", "post-quantum"]
std = [
    "alloc",
    "dcrypt-api/std", 
    "dcrypt-common/std", 
    "dcrypt-internal/std",
    "dcrypt-algorithms/std"
]
no_std = [
    "alloc",
    "dcrypt-api/no_std", 
    "dcrypt-common/no_std", 
    "dcrypt-internal/no_std"
]
alloc = ["dcrypt-api/alloc", "dcrypt-common/alloc", "dcrypt-internal/alloc", "dcrypt-algorithms/alloc"]
traditional = ["alloc", "dcrypt-algorithms/kdf"] # ECDSA, Ed25519, and BLS12-381
post-quantum = ["alloc"] # FIPS 204 ML-DSA

[dependencies]
dcrypt-api = { path = "../api", version = "=4.0.0", default-features = false }
dcrypt-common = { path = "../common", version = "=4.0.0", default-features = false }
dcrypt-internal = { path = "../internal", version = "=4.0.0", default-features = false }
dcrypt-params = { path = "../params", version = "=4.0.0" }
dcrypt-algorithms = { path = "../algorithms", version = "=4.0.0", default-features = false, features = ["alloc", "ec", "hash", "mac", "xof"] }

[dev-dependencies]
hex = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "mldsa"
harness = false
required-features = ["post-quantum"]

[package.metadata.release]
publish = true

[lints]
workspace = true
