[package]
name = "dcrypt-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Utilities and helpers for the dcrypt library"
repository.workspace = true
license.workspace = true
publish = true

[features]
default = ["std"]
std = [
    "alloc",
    "hex/std",
    "base64/std"
]
no_std = ["alloc"]
alloc = []  # Feature for allocation support in no_std environments

[dependencies]
hex = { version = "=0.4.3", default-features = false, features = ["alloc"] }
base64 = { version = "=0.22.1", default-features = false, features = ["alloc"] }

[package.metadata.release]
publish = true

[lints]
workspace = true
