[package]
name = "dcrypt-pke"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Public Key Encryption schemes for the dcrypt library"
repository.workspace = true
license.workspace = true
publish = true


[features]
default = ["std"]
std = [
    "dcrypt-api/std",
    "dcrypt-common/std",
    "dcrypt-internal/std",
    "dcrypt-algorithms/std",
    "alloc"          # The 'std' feature of 'pke' also implies 'alloc'
]
alloc = [
    "dcrypt-api/alloc",
    "dcrypt-common/alloc",
    "dcrypt-internal/alloc",
    "dcrypt-algorithms/alloc",
]
no_std = [
    "alloc",
    "dcrypt-api/no_std",
    "dcrypt-common/no_std",
    "dcrypt-internal/no_std",
]

[dependencies]
dcrypt-api = { path = "../api", version = "=3.0.0", default-features = false }
dcrypt-common = { path = "../common", version = "=3.0.0", default-features = false }
dcrypt-algorithms = { path = "../algorithms", version = "=3.0.0", default-features = false, features = ["alloc", "ec", "kdf", "aead", "hash", "mac", "stream"] }
dcrypt-internal = { path = "../internal", version = "=3.0.0", default-features = false }
dcrypt-params = { path = "../params", version = "=3.0.0" }

[package.metadata.release]
publish = true

[lints]
workspace = true
