#!/usr/bin/env python3
"""Generate the exact threat-model coverage map and human-readable document."""

from __future__ import annotations

import argparse
import sys

from threat_model_lib import (
    MODEL_PATH,
    ValidationError,
    expected_artifacts,
    format_errors,
    load_model_document,
    pretty_json_bytes,
    safe_generated_path,
    sha256_bytes,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated bytes are current without writing them",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    coverage, markdown, errors = expected_artifacts(mode="ci")
    if errors:
        print(format_errors(errors), file=sys.stderr)
        return 1
    models = load_model_document()
    try:
        coverage_path = safe_generated_path(
            models["generated-coverage"],
            label="generated-coverage",
            require_exists=args.check,
        )
        document_path = safe_generated_path(
            models["generated-document"],
            label="generated-document",
            require_exists=args.check,
        )
    except (KeyError, ValidationError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    coverage_bytes = pretty_json_bytes(coverage)
    if args.check:
        drift = []
        if coverage_path.read_bytes() != coverage_bytes:
            drift.append(str(coverage_path))
        if document_path.read_bytes() != markdown:
            drift.append(str(document_path))
        if drift:
            print(f"ERROR: generated threat-model artifact drift: {', '.join(drift)}", file=sys.stderr)
            return 1
        print(
            f"checked generated threat-model artifacts without writes: "
            f"exact_rows={len(coverage['rows'])}, release_blocked={coverage['counts']['release_blocked_rows']}"
        )
        return 0
    coverage_path.write_bytes(coverage_bytes)
    document_path.write_bytes(markdown)
    print(
        f"generated {coverage_path.relative_to(MODEL_PATH.parent)} "
        f"({len(coverage['rows'])} exact rows, sha256={sha256_bytes(coverage_bytes)})"
    )
    print(
        f"generated {document_path.relative_to(MODEL_PATH.parent)} "
        f"(sha256={sha256_bytes(markdown)})"
    )
    print(f"release blockers preserved: {coverage['counts']['release_blocked_rows']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
