[package]
name = "dcrypt-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Common implementations and shared functionality for the dcrypt library"
repository.workspace = true
license.workspace = true
publish = true

[features]
default = ["std"]
std = ["alloc", "dcrypt-api/std", "dcrypt-internal/std"]
alloc = ["dcrypt-api/alloc", "dcrypt-internal/alloc"]
no_std = []

[dependencies]
dcrypt-internal = { path = "../internal", version = "=2.0.0", default-features = false, features = ["alloc"] }
dcrypt-api = { path = "../api", version = "=2.0.0", default-features = false, features = ["alloc"] }

[dev-dependencies]
rand = { version = "0.8.6" }

[package.metadata.release]
publish = true

[lints]
workspace = true
