[package]
name = "dcrypt-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Public API traits and types for the dcrypt library"
repository.workspace = true
license.workspace = true
publish = true 

[features]
default = ["std"]
std = ["alloc", "dcrypt-internal/std"]
alloc = ["dcrypt-internal/alloc"]
no_std = []

[dependencies]
dcrypt-internal = { path = "../internal", version = "=4.0.0", default-features = false, features = ["alloc"] }

[package.metadata.release]
publish = true

[lints]
workspace = true
